##
# Project-specific CI environment dependencies
##

# services:
#
#   pg:
#     image: postgres:latest
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=pgusr
#       - POSTGRES_PASSWORD=pgpwd
#     restart: always
